xcist/main

.github/workflows/build.yml, catsim/CommonTools.py, catsim/GetMu.py, catsim/Phantom_NCAT.py, catsim/Phantom_Voxelized.py, catsim/Scatter_ConvolutionModel.py, catsim/Spectrum.py, catsim/Xray_Filter.py, catsim/__init__.py, examples/.catsim, examples/Sim_Sample.py, examples/validation/experiment_CatSimLogo_SimAndRecon/pyfiles/experiment_CatSimLogo.py, reconstruction/pyfiles/fdk_equiAngle.py, setup.py, sonar-project.properties
Ran examples/sim_Sample, examples/sim_Sample_Scatter and examples/validation/experiment_CatSimLog_SimAndRecon/pyfiles/experiment_CatSimLogo successfully locally.
=> Search paths

catsim/CommonTools.py, catsim/__init__.py, setup.py
Tested changes with @PaulFitzGerald.
=> Search recursive

clib_build/src/CrossSection.cpp
add acceleration for geant4 database loading
save geant4 database to a binary file in the first-time run and will load this binary database later to accelerate
=> accelerate geant4 database loading

clib_build/src/CrossSection.cpp
=> fixed a bug in load database

.coveragerc, .github/workflows/build.yml, catsim/__init__.py, requirements.txt, setup.py, sonar-project.properties, test_catsim/test_CheckModule.py, test_catsim/test_CommonTools.py
=> Add pytest and a few sample tests, include coverage results for sonar reporting

clib_build/MakeMacOS, clib_build/src/getMemorySize.cpp, clib_build/src/nCAT_main.c, setup.py
=> Test jobin2

gecatsim/tests/test_catsim/test_C_DD3Proj.py, gecatsim/tests/test_catsim/test_C_Materials_CrossSectionDB_Initialize.py, gecatsim/tests/test_catsim/test_C_Materials_CrossSectionMAC_ByProc_Get.py, gecatsim/tests/test_catsim/test_C_Projector_Analytic.py, gecatsim/tests/test_catsim/test_C_Projector_NCAT.py, gecatsim/tests/test_catsim/test_C_Projector_Voxelized.py, gecatsim/tests/test_catsim/test_C_Source_Analytic_Set.py, gecatsim/tests/test_catsim/test_C_Source_NCAT_Set.py, gecatsim/tests/test_catsim/test_C_Source_Voxelized_Set.py, gecatsim/tests/test_catsim/test_CalcCrossTalk.py, gecatsim/tests/test_catsim/test_CalcOptCrossTalk.py, gecatsim/tests/test_catsim/test_CatSim.py, gecatsim/tests/test_catsim/test_CommonTools.py, gecatsim/tests/test_catsim/test_Detection_EI.py, gecatsim/tests/test_catsim/test_Detection_Flux.py, gecatsim/tests/test_catsim/test_Detection_Lag.py, gecatsim/tests/test_catsim/test_Detection_prefilter.py, gecatsim/tests/test_catsim/test_Detector_RayAngles_2D.py, gecatsim/tests/test_catsim/test_Detector_ThirdgenCurved.py, gecatsim/tests/test_catsim/test_GetMu.py, gecatsim/tests/test_catsim/test_OneScan.py, gecatsim/tests/test_catsim/test_Phantom_Analytic.py, gecatsim/tests/test_catsim/test_Phantom_NCAT.py, gecatsim/tests/test_catsim/test_Phantom_Voxelized.py, gecatsim/tests/test_catsim/test_PrepView.py, gecatsim/tests/test_catsim/test_ReadMaterialFile.py, gecatsim/tests/test_catsim/test_Spectrum.py, gecatsim/tests/test_catsim/test_Xray_Filter.py, gecatsim/tests/test_catsim/test_randpf.py
=> Unittesting more

gecatsim/tests/test_catsim/test_C_DD3Proj.py, gecatsim/tests/test_catsim/test_C_Materials_CrossSectionDB_Initialize.py, gecatsim/tests/test_catsim/test_C_Materials_CrossSectionMAC_ByProc_Get.py, gecatsim/tests/test_catsim/test_C_Projector_Analytic.py, gecatsim/tests/test_catsim/test_C_Projector_NCAT.py, gecatsim/tests/test_catsim/test_C_Projector_Voxelized.py, gecatsim/tests/test_catsim/test_C_Source_Analytic_Set.py, gecatsim/tests/test_catsim/test_C_Source_NCAT_Set.py, gecatsim/tests/test_catsim/test_C_Source_Voxelized_Set.py, gecatsim/tests/test_catsim/test_CalcCrossTalk.py, gecatsim/tests/test_catsim/test_CalcOptCrossTalk.py, gecatsim/tests/test_catsim/test_CatSim.py, gecatsim/tests/test_catsim/test_CheckModule.py, gecatsim/tests/test_catsim/test_CommonTools.py, gecatsim/tests/test_catsim/test_Detection_EI.py, gecatsim/tests/test_catsim/test_Detection_Flux.py, gecatsim/tests/test_catsim/test_Detection_Lag.py, gecatsim/tests/test_catsim/test_Detection_prefilter.py, gecatsim/tests/test_catsim/test_Detector_RayAngles_2D.py, gecatsim/tests/test_catsim/test_Detector_ThirdgenCurved.py, gecatsim/tests/test_catsim/test_Gantry_Helical.py, gecatsim/tests/test_catsim/test_GetMu.py, gecatsim/tests/test_catsim/test_OneScan.py
=> Updated code to incorporate review comments.

.github/workflows/build.yml, sonar-project.properties
=> Sonartest fix final

.github/workflows/build.yml, sonar-project.properties
=> Revert "Sonartest fix final"

.coveragerc
=> Ignore all tests, not just test_catsim.

sonar-project.properties
=> Changes for sonar coverage.

.github/workflows/build.yml, sonar-project.properties
=> Sonar fix retest

.gitignore, gecatsim/pyfiles/OneScan.py, gecatsim/pyfiles/PhantomProjectorWrapper.py
added support for hybrid projector
=> add support for hybrid projector

gecatsim/tests/test_catsim/test_OneScan.py
Changed test case due to code changes in pull #62 https://github.com/xcist/main/commit/f21e64491748364fbdc1918fad962e1980e4dddf
=> Fixed testcases due to code changes in pull request 62.

.github/workflows/build.yml, gecatsim/tests/test_catsim/test_Spectrum.py, gecatsim/tests/test_catsim/test_Xray_Filter.py
=> updates on unit testcases for code change

gecatsim/tests/test_catsim/test_Detection_PC.py
=> unittestcase added for Detection_PC

gecatsim/tests/test_catsim/test_PhantomProjectorWrapper.py
=> Added tests for Hybrid Projector.

gecatsim/tests/test_functional/all_in_one_config.cfg, gecatsim/tests/test_functional/test_WaterPhantom.py
=> Added Functional Test for Water Phantom.

gecatsim/tests/test_functional/test_WaterPhantom.py
=> Added line.

gecatsim/tests/test_catsim/test_OneScan.py, gecatsim/tests/test_catsim/test_Prep_BHC_Accurate.py, gecatsim/tests/test_catsim/test_ReadMaterialFile.py, gecatsim/tests/test_catsim/test_Scatter_ConvolutionModel.py, gecatsim/tests/test_catsim/test_Scatter_Correction.py, gecatsim/tests/test_catsim/test_WriteRawViewChunk.py, gecatsim/tests/test_functional/test_WaterPhantom.py
=> Functional test

gecatsim/tests/test_catsim/test_C_Projector_Polygon.py
Added unittestcase for C_Projector_Polygon, which is missing in master
=> C_Projector_Polygon unittest added

.github/workflows/build.yml
=> Disable functional tests workflow only

gecatsim/reconstruction/pyfiles/recon.py
=> Factor out and expose direct reconstruction

gecatsim/reconstruction/pyfiles/recon.py
Earlier, image saving was removed when factoring out the reconstruction function. This re-adds that.
=> Re-adds removed image saving

gecatsim/examples/mtf_examples/Phantom_Sample_Analytic.cfg, gecatsim/examples/mtf_examples/Protocol_Sample_axial.cfg, gecatsim/examples/mtf_examples/Scanner_Sample_generic.cfg, gecatsim/tests/test_functional/test_SpacialResolution.py
=> Added new functional test case created by Saradee.
